import { z } from "zod";
import {
  AiPattern,
  DataClassification,
  NdaStatus,
  SecurityReviewStatus,
} from "@prisma/client";

export const intakeFormSchema = z.object({
  title: z.string().optional(),
  businessUnit: z.string().optional(),
  executiveSponsorName: z.string().optional(),
  executiveSponsorTitle: z.string().optional(),
  problemStatement: z.string().optional(),
  proposedSolution: z.string().optional(),
  expectedBenefits: z.string().optional(),
  aiPattern: z.nativeEnum(AiPattern).optional().nullable(),
  autonomyLevel: z.coerce.number().min(1).max(5).optional().nullable(),
  currentProcessDescription: z.string().optional(),
  currentFtes: z.coerce.number().optional().nullable(),
  currentVolume: z.string().optional(),
  currentCycleTime: z.string().optional(),
  currentErrorRate: z.coerce.number().optional().nullable(),
  annualCost: z.coerce.number().optional().nullable(),
  knownPainPoints: z.string().optional(),
  sourceSystemsText: z.string().optional(),
  readSystems: z.string().optional(),
  writeSystems: z.string().optional(),
  ingestionMethod: z.string().optional(),
  ingestionFrequency: z.string().optional(),
  dataVolume: z.string().optional(),
  historicalRequired: z.boolean().optional().nullable(),
  historicalLookback: z.string().optional(),
  dqIssues: z.string().optional(),
  remediationNeeded: z.boolean().optional().nullable(),
  remediationPlan: z.string().optional(),
  dqOwnership: z.string().optional(),
  businessDomains: z.array(z.string()).optional(),
  masterRefData: z.string().optional(),
  modelRelationship: z.string().optional(),
  auditabilityRequired: z.boolean().optional().nullable(),
  auditabilityDetail: z.string().optional(),
  policyReviewRequired: z.boolean().optional().nullable(),
  policyReviewBody: z.string().optional(),
  ndaStatus: z.nativeEnum(NdaStatus).optional().nullable(),
  dataOwner: z.string().optional(),
  dataSteward: z.string().optional(),
  retentionPolicy: z.string().optional(),
  regulatoryConsiderations: z.string().optional(),
  dataClassification: z.nativeEnum(DataClassification).optional().nullable(),
  accessControlReqs: z.string().optional(),
  piiCuiPresent: z.boolean().optional().nullable(),
  piiCuiDetail: z.string().optional(),
  encryptionReqs: z.array(z.string()).optional(),
  govtModelAccess: z.boolean().optional().nullable(),
  securityReviewStatus: z.nativeEnum(SecurityReviewStatus).optional().nullable(),
  reportingReqs: z.string().optional(),
  endUserPersonas: z.string().optional(),
  conversationalAiRequired: z.boolean().optional().nullable(),
  conversationalAiDetail: z.string().optional(),
  accessChannels: z.array(z.string()).optional(),
  downstreamConsumption: z.string().optional(),
  submitterPriority: z.string().optional(),
  submitterComplexity: z.string().optional(),
  estimatedTimeline: z.string().optional(),
  dependenciesRisks: z.string().optional(),
  recommendedAction: z.string().optional(),
  nextStepsOwner: z.string().optional(),
  followUpDate: z.string().optional(),
  customFields: z.record(z.string(), z.unknown()).optional(),
});

export type IntakeFormValues = z.infer<typeof intakeFormSchema>;

export const useCaseUpdateInputSchema = intakeFormSchema.partial();
